joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 60

joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: Shoulder_01
  pid: {p: 20000.0, i: 0.0, d: 0.0}
  
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: Shoulder_02
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: Arm_01
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: Arm_02
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: Arm_03
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: Wrist
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: Hand
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_01_A
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint9_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_01_B
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint10_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_02_A
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint11_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_02_B
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint12_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_03_A
  pid: {p: 50000.0, i: 0.0, d: 0.0}

joint13_position_controller:
  type: effort_controllers/JointPositionController
  joint: Finger_03_B
  pid: {p: 50000.0, i: 0.0, d: 0.0}