joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_postion_controller:
  type: effort_controllers/JointPositionController
  joint: Shoulder_Up_Down
  pid: {p: 700, i: 50, d: 70}
#joint2_postion_controller:
 # type: effort_controllers/JointPositionController
  #joint: ink_01__link_02
  #pid: {p: 700, i: 50, d: 70}