joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Leg
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: lp_leg_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}

#Leg
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: rp_leg_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}

#Leg
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: lt_leg_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}

#Leg
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: rt_leg_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}
  

