# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: armRest
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Shoulder_01
    - Shoulder_02
    - Arm_01
    - Arm_02
    - Arm_03
    - Wrist
    - Hand
    - Finger_01_A
    - Finger_01_B
    - Finger_02_A
    - Finger_02_B
    - Finger_03_A
    - Finger_03_B
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Shoulder_01
      - Shoulder_02
      - Arm_01
      - Arm_02
      - Arm_03
      - Wrist
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Hand
      - Finger_01_A
      - Finger_01_B
      - Finger_02_A
      - Finger_02_B
      - Finger_03_A
      - Finger_03_B